Ft/skills
UmutesiMMA/ojembaProject pull request #13
Opened 2023-08-21 14:15 UTC by AdelineA

- add header
- add a team photo
- add team description
- add mobile responsiveness
- add medium screen responsiveness
- add desktop responsiveness

2023-08-21 15:48 UTC, gsngdavid requested changes
Almost there, just a few changes🤏

1. Title gets out of the container when screen is zoomed out

<img width="392" alt="Screenshot 2023-08-21 174051" src="https://github.com/UmutesiMMA/ojembaProject/assets/89668775/b7b20881-1abf-4c5b-ba8e-802439e6cf07">

2. Blueish background

<img width="373" alt="Screenshot 2023-08-21 173343" src="https://github.com/UmutesiMMA/ojembaProject/assets/89668775/695cd704-8871-430d-a680-9ca1fee69024">

**Figma**:
<img width="439" alt="Screenshot 2023-08-21 173408" src="https://github.com/UmutesiMMA/ojembaProject/assets/89668775/1947aa3c-2b38-4e60-8fd9-124983b16c95">

3. Optional: Consinder centering images in small screen
<img width="270" alt="Screenshot 2023-08-21 174458" src="https://github.com/UmutesiMMA/ojembaProject/assets/89668775/84958f81-395c-4e07-845e-f36d2e18130b">

2023-08-21 15:48 UTC, gsngdavid commented on build/sections/skills.html
> +        <h1>Eine mögliche T<span class="border-b-4 border-primary-green">eamkonstellation</h1></span>
Few changes.🤏

- Use right font-family (Raleway)
- Use right underline style ( check figma design)

2023-08-22 17:30 UTC, UmutesiMMA requested changes
<img width="328" alt="image" src="https://github.com/UmutesiMMA/ojembaProject/assets/133501822/f436f49c-a686-4b71-8ad5-24eeffa74621">

there's an extra black line that I highlighted in red. I suggest you remove it as it was't part of the figma design , I put a screenshot of the figma design for reference

Optional: may you increase the gap between the columns? I highlighted in green the slight difference between what you have and what was in the figma design
<img width="328" alt="image" src="https://github.com/UmutesiMMA/ojembaProject/assets/133501822/a780aed8-c8b0-480b-8dad-06f3a84a478d">

2023-08-23 12:56 UTC, UmutesiMMA approved these changes

2023-08-23 13:07 UTC, gsngdavid approved these changes
![well-done-despicable-me](https://github.com/UmutesiMMA/ojembaProject/assets/89668775/22fb093b-cd97-4dda-9b23-6291e4d088a3)

2023-08-23 13:13 UTC, merged