Hero Section
UmutesiMMA/ojembaProject pull request #2
Opened 2023-08-15 12:37 UTC by gsngdavid

2023-08-17 18:38 UTC, UmutesiMMA requested changes
Hi @gsngdavid 

**CHANGES REQUIRED** 🤏🏾🤏🏾

![so-close-keegan-michael-key](https://github.com/UmutesiMMA/ojembaProject/assets/133501822/5755d43c-211e-47ec-a271-c129d24eb3df)

- Below is the Figma design, When i compare it with yours some words are taking more width. Kindly check the screenshot below this one.

<img width="353" alt="image" src="https://github.com/UmutesiMMA/ojembaProject/assets/133501822/00b19233-9b03-4a94-9f7d-0dc90197c569">


- I have highlighted the areas that I feel need to be adjusted slightly. Kindly check out the image below. 

<img width="353" alt="image" src="https://github.com/UmutesiMMA/ojembaProject/assets/133501822/08af2fad-d853-4036-8b46-219ad91f7839">

- Kindly feel free to reach out to me in case there is something you aren't understanding.
_Happy Coding_ 🎊 🎊

2023-08-21 15:40 UTC, AdelineA requested changes
Your section looks perfect but you may look at the following:
- You may check provided fonts in Figma and use them where needed.
- On both mobile and md you may increase the padding top so as to make it look perfect.

2023-08-21 15:40 UTC, AdelineA commented on build/sections/hero.html
> +        </div>
Looks good, but you forgot to use the fonts they provided in Figma, you may check and apply them where needed.

2023-08-21 15:40 UTC, AdelineA commented on build/sections/hero.html
> +        </div>
Same as here, no fonts applied!!

2023-08-21 15:40 UTC, AdelineA commented on build/sections/hero.html
> +        </div>
Same as here too, fonts!

2023-08-21 15:40 UTC, AdelineA commented on build/sections/hero.html
> +        <p class="text-center xl:text-left mt-3 text-white">Erweiteren Sie Ihre Entwicklungsteams mit Ojemba</p>
Here, you forgot to use the fonts (both size and family).

2023-08-22 18:04 UTC, UmutesiMMA approved these changes
Well done🤝🏾

2023-08-23 12:44 UTC, AdelineA approved these changes
Job well done!

2023-08-23 12:54 UTC, merged