Ft/teams
UmutesiMMA/ojembaProject pull request #7
Opened 2023-08-17 12:54 UTC by AdelineA

- Add bg image
- add heading
- Add text
- Add video Image
- add heading
- add a list of skills
- add heading
- Add both mobile and desktop responsiveness

2023-08-18 17:02 UTC, gasangw requested changes
Hi @AdelineA 

# CHANGES REQUIRED 🟢 
- Great work done on the desktop version ✅ 
- Great design of the medium screen and mobile design. ✅ 

## However below are the changes required 🔴 

- This is your design. Kindly compare it with the figma design below this. I have highlighted a few areas to change and marked them out for you.

![Screenshot (21)](https://github.com/UmutesiMMA/ojembaProject/assets/99269832/da53c9af-5b3a-4ae3-9aa9-a9dd1a7f2786)

- Figma design is here. Compare it with your above design and make a few changes

![Screenshot (22)](https://github.com/UmutesiMMA/ojembaProject/assets/99269832/fa51bec8-e2dc-40bb-aaab-00dd8024a310)

- Kindly re-structure this section of the skill set to look well on the mobile section. There are many gaps between the skillset buttons.

![Screenshot (25)](https://github.com/UmutesiMMA/ojembaProject/assets/99269832/473fb072-b694-402a-afd3-cbff076df879)

2023-08-18 17:02 UTC, gasangw commented on build/sections/team.html
> +      <h1 class="font-raleway text-xl md:text-2xl lg:text-[36px] font-[700]">Unsere <span class="text-primary-green">Teams</span>  </h1>
- [OPTIONAL]  Kindly always check the Tailwindcss document for some features you are unsure of exist. For example, you declared the font-weight of `700` like `font-[700]` yet TailwindCSS has an inbuilt class for that which is `font-bold`. For more information about font weight feel free to check out this link. [font-weight](https://tailwindcss.com/docs/font-weight).

2023-08-18 17:02 UTC, gasangw commented on build/sections/team.html
> +         <p class="font-raleway pb-6 font-medium text-base sm:text-lg lg:text-[20px] pt-10">Einblick in die M<span class="border-b-4 border-primary-green shadow-xl">otivation und den Drive u</span>ns
- [OPTIONAL]  Kindly always check the Tailwindcss document for some features you are unsure of that exist. For example, you declared the font size of `20px` like `text-[20px]` yet TailwindCSS has an inbuilt class for that which is `text-sm`. For more information about font size feel free to check out this link. [font-size](https://tailwindcss.com/docs/font-size)

2023-08-18 17:02 UTC, gasangw commented on build/sections/team.html
> +         <h3 class="text-primary-green text-[16px] font-[900] pt-5">ZUM TECH-SKIlLPROFIL</h3>
- Kindly check out the comments above on inbuilt classes of `font size` and `font weight`. They can help you improve this line of code well.

2023-08-18 18:20 UTC, UmutesiMMA requested changes
<img width="227" alt="image" src="https://github.com/UmutesiMMA/ojembaProject/assets/133501822/c8083f48-64df-4863-a2d2-786c4beaf83e">
<img width="227" alt="image" src="https://github.com/UmutesiMMA/ojembaProject/assets/133501822/95d00e67-c460-4412-b02a-f8b4d47628ea">


I suggest arranging those list items in  such a way that the circled space is not  big
and increasing the bottom padding of you div (after the ZUM TECH ....) for better visibility in mobile view.
![image](https://github.com/UmutesiMMA/ojembaProject/assets/133501822/2c393224-c8c0-4bfb-885f-cf6ad3c897ad)


otherwise, it looks great!!🤝🏾🤝🏾
![leonardo-di-caprio-wolf-of-wall-street](https://github.com/UmutesiMMA/ojembaProject/assets/133501822/11606cc9-13d0-41ab-a561-3f4da1658e11)

2023-08-23 11:06 UTC, gasangw approved these changes
Hi @AdelineA 

## Congratulations 💯 

![excellent-work-inside-job](https://github.com/UmutesiMMA/ojembaProject/assets/99269832/15b7e794-133f-4f85-8605-395d5601e2c6)

- Thanks for Implementing the changes I had requested. To me its now complete and ready for merging.

2023-08-23 13:28 UTC, UmutesiMMA approved these changes

2023-08-23 13:30 UTC, merged